name: VanishV2
main: superbobby\VanishV2\VanishV2
api: 3.0.0
mcpe-protocol: [389]
version: "1.0"
author: superbobby
commands:
  vanish:
    description: "Vanish yourself"
    permission: "vanish.use"
  v:
    description: "Vanish yourself"
    permission: "vanish.use"
permissions:
  vanish.use:
    description: "Vanish use perm"
    default: op
  vanish.see:
     description: "Vanish see perm"
     default: op
